import os
import glob

replacements = {
    "Система принятия кредитных решений с объяснением факторов": "{{ t('index.title') }}",
    "Всего заявок": "{{ t('index.stats.total') }}",
    "Train (обучение)": "{{ t('index.stats.train') }}",
    "Test (оценка)": "{{ t('index.stats.test') }}",
    "Уровень дефолта": "{{ t('index.stats.default_rate') }}",
    "Статус портфеля": "{{ t('index.charts.status') }}",
    "Распределение баллов (Колокол)": "{{ t('index.charts.scores') }}",
    "ТОП-5 Причин отказов": "{{ t('index.charts.reasons') }}",
    "Модель": "{{ t('index.cards.model') }}",
    "Версия:": "{{ t('index.cards.version') }}",
    "Дата обучения:": "{{ t('index.cards.date') }}",
    "Порог одобрения:": "{{ t('index.cards.threshold') }}",
    "Подробнее →": "{{ t('index.cards.more') }}",
    "Быстрые действия": "{{ t('index.cards.actions') }}",
    "Подать заявку": "{{ t('index.cards.action.apply') }}",
    "Панель андеррайтера": "{{ t('index.cards.action.underwriter') }}",
    "What-If симулятор": "{{ t('index.cards.action.whatif') }}",
    "Алгоритмы": "{{ t('index.cards.algo') }}",
    "DTI/PTI расчёт": "{{ t('index.cards.algo.dti') }}",
    "Cash-flow анализ (CV)": "{{ t('index.cards.algo.cv') }}",
    "WOE/IV биннинг": "{{ t('index.cards.algo.woe') }}",
    "Логистическая регрессия": "{{ t('index.cards.algo.logreg') }}",
    "Binary search лимита": "{{ t('index.cards.algo.binary') }}",
    "Объяснение факторов": "{{ t('index.cards.algo.factors') }}",
    "Рассчитать решение": "{{ t('form.submit') }}",
    "← Возврат в базу": "{{ t('btn.back') }}",
    "What-If анализ": "{{ t('btn.whatif') }}",
    "ОДОБРЕНО": "{{ t('status.approved') }}",
    "ОТКАЗАНО": "{{ t('status.rejected') }}",
    "Возраст": "{{ t('f.age') }}",
    "Пол": "{{ t('f.gender') }}",
    "Мужской": "{{ t('f.gender.m') }}",
    "Женский": "{{ t('f.gender.f') }}",
    "Регион": "{{ t('f.region') }}",
    "Тип занятости": "{{ t('f.employment') }}",
    "Частный сектор": "{{ t('f.employment.priv') }}",
    "Бюджет": "{{ t('f.employment.gov') }}",
    "IT-сфера": "{{ t('f.employment.it') }}",
    "Торговля": "{{ t('f.employment.trade') }}",
    "Строительство": "{{ t('f.employment.construct') }}",
    "Транспорт": "{{ t('f.employment.trans') }}",
    "Самозанятый": "{{ t('f.employment.self') }}",
    "Безработный": "{{ t('f.employment.unemp') }}",
    "Образование": "{{ t('f.edu') }}",
    "Высшее": "{{ t('f.edu.higher') }}",
    "Средне-специальное": "{{ t('f.edu.special') }}",
    "Среднее": "{{ t('f.edu.mid') }}",
    "Стаж работы (месяцев)": "{{ t('f.exp') }}",
    "Декларированный доход (UZS)": "{{ t('f.income_decl') }}",
    "Подтвержденный расчетный доход": "{{ t('f.income_med') }}",
    "Нестабильность дохода (CV)": "{{ t('f.income_cv') }}",
    "Членов семьи": "{{ t('f.family') }}",
    "Срок клиентства (месяцев)": "{{ t('f.client_len') }}",
    "Запрашиваемая сумма": "{{ t('f.amount') }}",
    "Цель": "{{ t('f.purpose') }}",
    "Потребительский": "{{ t('f.purpose.consum') }}",
    "Автокредит": "{{ t('f.purpose.auto') }}",
    "Ипотека": "{{ t('f.purpose.mortgage') }}",
    "Кредитная карта": "{{ t('f.purpose.card') }}",
    "Срок (месяцев)": "{{ t('f.term') }}",
    "Текущий платеж (заявка)": "{{ t('f.curr_pay') }}",
    "Платеж по открытым кредитам": "{{ t('f.ext_pay') }}",
    "Остаток долга": "{{ t('f.ext_debt') }}",
    "Максимальная просрочка (дней)": "{{ t('f.max_delinq') }}",
    "Финальное решение": "{{ t('det.decision') }}",
    "Сводка кредитоспособности": "{{ t('det.summary') }}",
    "Скоринговый балл": "{{ t('det.score') }}",
    "Вероятность дефолта": "{{ t('det.pd') }}",
    "Одобренный лимит": "{{ t('det.limit') }}",
    "Основные факторы": "{{ t('det.factors') }}",
    "Фактор": "{{ t('det.factor.name') }}",
    "Значение клиента": "{{ t('det.factor.val') }}",
    "Среднее по базе": "{{ t('det.factor.base') }}",
    "Баллы": "{{ t('det.factor.pts') }}",
    "Причины отказа для клиента": "{{ t('det.reject_reasons') }}",
    "Симулятор отклонений": "{{ t('whatif.title') }}",
    "Как изменение параметров повлияет на скоринговый балл?": "{{ t('whatif.desc') }}",
    "Симулировать": "{{ t('whatif.simulate') }}",
    "Оценка потока заявок": "{{ t('uw.desc') }}",
    "ID Заявки": "{{ t('uw.table.id') }}",
    "Клиент": "{{ t('uw.table.client') }}",
    "Сумма": "{{ t('uw.table.amount') }}",
    "Балл (Score)": "{{ t('uw.table.score') }}",
    "Риск": "{{ t('uw.table.pd') }}",
    "Решение": "{{ t('uw.table.decision') }}",
    "Анализ": "{{ t('uw.table.view') }}",
    "Информация о модели": "{{ t('model.info.title') }}",
    "Whitebox параметры логистической регрессии и Scorecard-калибровки": "{{ t('model.info.desc') }}",
    "Scorecard Параметры": "{{ t('model.params') }}",
    "Ступень баллов (Factor)": "{{ t('model.factor') }}",
    "Смещение (Offset)": "{{ t('model.offset') }}",
    "Интерцепт (Intercept)": "{{ t('model.intercept') }}",
    "Веса логистической регрессии (Log Odds)": "{{ t('model.coef.title') }}",
    "Признак": "{{ t('model.table.feat') }}",
    "Коэффициент": "{{ t('model.table.coef') }}",
    "Значимость (IV)": "{{ t('model.table.iv') }}",
    "Влияние на риск": "{{ t('model.table.impact') }}",
    "Снижает дефолт": "{{ t('model.impact.pos') }}",
    "Повышает дефолт": "{{ t('model.impact.neg') }}",
    "Схема данных (ERD)": "{{ t('erd.title') }}",
    "Структура данных MVP: связи между Applicants, Applications, Flows и Loans": "{{ t('erd.subtitle') }}",
    "Словарь сгенерированных признаков": "{{ t('erd.dict.title') }}",
    "Эти показатели не лежат в сыром виде в базе, а вычисляются из связанных таблиц транзакций и кредитов. Именно они подаются в ML-модель после Target Encoding.": "{{ t('erd.dict.desc') }}",
    "Фактор (Feature)": "{{ t('erd.col.fact') }}",
    "Источник / Формула": "{{ t('erd.col.form') }}",
    "Весомость": "{{ t('erd.col.weight') }}",
    "Описание и влияние": "{{ t('erd.col.desc') }}"
}

for filepath in glob.glob("templates/*.html"):
    if filepath.endswith("base.html"):
        continue
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()
    
    for ru_text, jinja_tag in replacements.items():
        content = content.replace(ru_text, jinja_tag)
        
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)
